language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install dash
  - pip install coverage
script: coverage run -m unittest travisci_and_codecov_example/tests/test_addition.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
